repos:
    - repo: https://github.com/thoughtworks/talisman
      rev: 'v1.2.0'
      hooks:
          - id: talisman-commit
    - repo: https://github.com/PyCQA/bandit
      rev: '1.6.2'
      hooks:
          - id: bandit
            args: [-c, .bandit.yml, -r, -l]
    - repo: https://gitlab.com/pycqa/flake8
      rev: '3.7.7'
      hooks:
        - id: flake8