name: Load test

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke load test
        shell: bash {0}
        run: |
          INSTANCE_ID=$(aws ssm get-parameter --name /utility/locust/instance | jq '.Parameter.Value' -r)
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids $INSTANCE_ID \
            --parameters '{"commands":[
                "#!/bin/bash",
                "locust -f notification-api/load_testing/locustfile.py --headless -u 1 -r 1 --host http://dev.api.notifications.va.gov --run-time 5s"
              ]}' \
            --output text --query "Command.CommandId")
          aws ssm wait command-executed --command-id $COMMAND_ID --instance-id $INSTANCE_ID ; \
          RESULT=$(aws ssm list-command-invocations \
            --command-id $COMMAND_ID \
            --details \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,StatusDetails:StatusDetails,ResponseCode:ResponseCode,Output:Output}")
          echo $RESULT
          exit `jq '.[].ResponseCode' <<< $RESULT`
